### PR TITLE
No native

### PR DESCRIPTION
**Pull request by davidlehn**

### CODE REVIEW

**Comment by mattcollier** [comment]
The PR looks fine, but I do have concerns about this general approach.  As I understand it, if `rdf-canonize-native` gets installed by any of my deps or sub-deps, it's going to be used automatically in places where that behavior is not desired expected.

**Comment by mattcollier** [comment]
I feel like the API need to be something like, I install the `rdf-canonize-native` dep and I must then state explicitly that I want to use it provided that it *is* installed.

**Comment by davidlehn** [comment]
@mattcollier Yes, I think this needs improvement too.  Right now it will just match current behavior.  I thought about adding a `useNative` option to force that mode vs the `usePureJavaScript`.  If we had more options I'd switch it to a mode string or something.  The problem with all this is that it's a challenge to configure modules that are a layer deep.  Annoying to expose the details to jsonld users.  Your suggestion to set the rdf-canonize lib to use is a problem if you want to leverage the rdf-canonize support to use js as needed, for instance for other algorithms than what the native code supports.

**Comment by mattcollier** [comment]
I think that the `useNative` flag is the right/better approach.  So regardless of package manager side-effects js is *always* the default and one must install rdf-canonize-native *AND* specify the `useNative` flag if they want to use the native implementation.  And under those circumstances, I think it would be expected that if I specify the `useNative` flag and the native module is not found, or the native module does not support the operation that the code would throw.

**Comment by davidlehn** [comment]
Yeah, I think if these flags exist it should do exactly what they say.  Is a `usePureJavaScript` flag needed too?  What would the jsonld.js api look like to use this?  (Since that's our normal interface to this code.)

For historical reference, I think we went with the `usePureJavaScript` approach since the native code was faster at the time and we wanted to force it the js way.  It also lines up with a similar forge flag.

**Comment by davidlehn** [comment]
Need another look at this. I just flipped the logic so it's JS by default now and requires both rdf-canonize-native to be available and useNative=true if you want native code. Is that better?

**Pull request merged**
